apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: greeting-console
spec:
  nodeSelector: {}
  source:
    type: Git
    git:
      uri: 'https://github.com/larryklean/do400-greeting-console.git'
      ref: main
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: nodejs:10
        namespace: openshift
  output:
    to:
      kind: DockerImage
      name: quay.io/oolaleyee/greeting-console
    pushSecret:
      name: quay-credentials

